### ISSUE TITLE
Jimu UI components

### ISSUE THREAD

**Issue by nathanhannig** [gavinr/the-one-widget#20]
With this approach, is there a way to be able to use the jimu-ui component library for the standalone React app?

**Comment by gavinr** [comment]
Interesting, thanks for the question.

A higher-level question where we can start: **_can you use the `jimu-ui` library outside of Experience Builder?_** I'm not sure of that answer but can try to get one.

If we get a positive response to that question, then in theory it's just figuring out the technical steps needed to get the jimu-ui library as a dependency in the standalone react widget.

**Comment by gavinr** [comment]
I checked with the team, we do not think `jimu-ui` can be used outside of Experience Builder right now since it has dependencies on other libraries that are in Experience Builder.
